---
- name: "Changer target"
  hosts: all

  tasks:
    - name: "changer target"
      file:
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link
