---
- name: "hproxy"
  hosts: 172.19.10.164
  gather_facts: yes
#  become: yes
  vars:

    haproxy_backend_servers:
      - name: ansible
        address: localhost:8080
      - name: ansible
        address: 172.19.10.73:8080



  roles:
    - haproxy
      # essaie:
      #
      #
      #
      #
      #
      #
      # le role attend les variables haproxy_backend ... pour savoir les @ip des serveurs du load balancing; on les a passés via les vars
      #

