---
- name: Installation de Httpd et Apache2 
  hosts: all
  gather_facts: yes
  # become: yes 
  tasks:
    - name: "Mettre à jour tous les paquets, installationde httpd et  Personnalisation de  la page d'accueil pour le groupe projet"
      block:
        - name: "1) Mettre à jour tous les paquets" 
          yum:
            name: "*"
            state: latest
        - name: "2) installationde httpd" 
          yum:
            name: httpd
            state: latest
          notify: httpd_restart 
            
      when: "'projet' in group_names"
    
    
    - name: "Mettre à jour tous les paquets, installationde httpd et  Personnalisation de  la page d'accueil pour le groupe test"
 
      block:
        - name: "1) Mettre à jour tous les paquets"
          apt:
            name: "*"
            state: latest

        - name: "2) installationde httpd"    
          apt:
            name: apache2
            state: latest
          notify: apache2_restart

      when: "'test' in group_names"
      
    - name: "Personnalisation de  la page d'accueil"
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644

      # des Handlers de déclanche si on a des modif ds linstallation de httpd et apache2 
      
      
      

  handlers:
    - name: httpd_restart
      service:
        name: httpd
        state: restarted
    
    - name: apache2_restart
      service:
        name: apache2
        state: restarted


