---
- name: creation des users Question 5
  hosts: all
  #become: yes
  vars_files:
    - "user_vars.yml"
    - "mdp.yml"
  tasks:
  
    - name: " creation de groupe dev"
      group: 
        name: "dev"  

        state: present
      when: "'projet' in group_names"

    - name: " creation de groupe test"
      group: 
        name: "test"
        state: present
      when: "'test' in group_names"



    - name: " creation des  users Type dev "
      user:
        name: "{{ item.username }}"
        groups: "{{ item.Type }}"
        password: "{{ password_dev | password_hash('sha512') }}"
        state: present
      when: (item.Type == 'dev' and 'projet' in group_names) 
      loop: "{{ users }}"


     
    - name: " creation des  users Type Test "
      user:
        name: "{{ item.username }}"
        groups: "{{ item.Type }}"
        password: "{{ password_test | password_hash('sha512') }}"
        state: present
      when: (item.Type  == 'test' and "test" in group_names)
      loop: "{{ users }}"  
